### PR TITLE
Added API Documentation using YARD

### PR DESCRIPTION
**Pull request by rbharatc**
Ready for Review.

### CODE REVIEW

**Comment by jemc** [comment]
Thanks!  Though I'm not sure that we want to be committing the generated `html` files into the repo.  I'd prefer to exclude those `html` files from `git`, and add a rule to the `.gitignore` so that they won't get picked up again.

**Comment by rbharatc** [comment]
Sure @jemc! I will remove the `docs` folder and add rules for `html`, `css` and `js` to `.gitignore`. 
Also, shall I do the same with Ruby and mRuby too?

**Comment by jemc** [comment]
Yes, please.

Thanks for tackling this!

Closes #6.

**Comment by rbharatc** [comment]
Ready for Review.

**Pull request merged**
